### PR TITLE
add summernote to admin and fix episode titles in admin and add to gi…

### PR DESCRIPTION
**Pull request by jinpark**
…tignore

for #13

### CODE REVIEW

**Comment by jinpark** [comment]
looks like

image

**Comment by billyfung** [comment]
how do you use it? Like if I want to display bulleted list with a url

**Comment by jinpark** [comment]
pull it down,

> pip install -r requirements.txt
> python manage.py migrate
> python manage.py runserver

go to the admin and try it out

**Comment by billyfung** [comment]
and then in the html file you put `{{ episode.show_notes }}` and that's it?

**Comment by jinpark** [comment]
updated with correct filter

**Comment by billyfung** [comment]
alright this looks good, cool stuff!

**Pull request merged**
